### ISSUE TITLE
building documentation does not work on windows due to issues parsing paths

### ISSUE THREAD

**Issue by flothesof** [sfepy/sfepy#905]
I am using sfepy on windows. 
While trying to build the documentation, I had to modify a couple of things to get it to build, since the paths are written from a unix perspective and not compatible with windows.

I have committed the changes I had to apply to get at least parts of the documentation to build here:
https://github.com/flothesof/sfepy/tree/fix_windows_issues

**Comment by rc** [comment]
Thanks for the report! Besides the setup.py change, would you be interested in making a PR?

**Comment by flothesof** [comment]
Hi again.
Yes, I’ll try submitting a PR.

**Comment by flothesof** [comment]
Actually, I’m stumbling on another problem when building the gallery using gen_gallery.py.
Here’s what happens:
- acoustics.py runs fine
- acoustics3d.py errors at the plotting stage

I inspected with the debugger and the problem comes from the main loop of gen_gallery.
It tries to open result.vtk in a temp folder.
However, acoustics3d does not generate a file called result.vtk. Instead, I find two different vtk files in the corresponding temp folder: result_Omega_1.vtk and result_Omega_2.vtk
So the error makes sense to me.

My question: how does the generate gallery script create a visualization adding several meshes together ? 
I’m assuming that this should come from `filename = problem.get_output_name(suffix=suffix)` but in my case this does holds a path to a file that doesn’t exist...

Any ideas?

**Comment by rc** [comment]
The example acoustics3d.py should generate two files named `result_Omega_1.vtk`, ` result_Omega_2.vtk`. Then, my session works as follows (I added `print(filename)`):
```
/tmp/tmppn1jsqec/result.vtk
sfepy:   displaying results from "/tmp/tmppn1jsqec/result_Omega_1.vtk"
sfepy:   to "doc/images/gallery/acoustics-acoustics3d_Omega_1.png"...
mesh from /tmp/tmppn1jsqec/result_Omega_1.vtk:
  points:  1107
  cells:   780
  bounds:  [(0.0, 0.0245), (0.0, 0.0245), (0.0, 0.157981)]
  scalars: real.p_1, imag.p_1, node_groups, mat_id
  steps:   1
plot 0: real.p_1(step 0)
plot 1: imag.p_1(step 0)
sfepy:   displaying results from "/tmp/tmppn1jsqec/result_Omega_2.vtk"
sfepy:   to "doc/images/gallery/acoustics-acoustics3d_Omega_2.png"...
mesh from /tmp/tmppn1jsqec/result_Omega_2.vtk:
  points:  4318
  cells:   3600
  bounds:  [(0.0, 0.0822), (0.0, 0.0822), (0.03, 0.127981)]
  scalars: real.p_2, imag.p_2, node_groups, mat_id
  steps:   1
plot 0: real.p_2(step 0)
plot 1: imag.p_2(step 0)
sfepy:   ...done
```
Can you show your output? You can limit the loop
```
for ex_filename in locate_files('*acoustics3d.py', examples_dir):
...
```
to check just the one example.

**Comment by flothesof** [comment]
Here’s my output (I added the print as you did):
```python-traceback
C:\Users\FL232714\AppData\Local\Temp\tmp9_79fnzj\result.vtk
sfepy:   displaying results from "C:\Users\FL232714\AppData\Local\Temp\tmp9_79fnzj\result.vtk"
sfepy:   to "doc\images/gallery\acoustics-acoustics3d.png"...
Traceback (most recent call last):
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\tools\gen_gallery.py", line 662, in <module>
    main()
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\tools\gen_gallery.py", line 652, in main
    generate_images(images_dir, examples_dir)
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\tools\gen_gallery.py", line 380, in generate_images
    resview_plot(fname, fig_filename, kwargs)
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\tools\gen_gallery.py", line 189, in resview_plot
    plotter = pv_plot([filename], options, plotter=plotter, use_cache=False)
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\sfepy\scripts\resview.py", line 328, in pv_plot
    mesh, n_steps = read_mesh(filenames, fstep, ret_n_steps=True,
  File "C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\sfepy\scripts\resview.py", line 161, in read_mesh
    cache[key] = pv.UnstructuredGrid(fname)
  File "C:\Anaconda3\envs\sfepy_py38_env\lib\site-packages\pyvista\core\pointset.py", line 1344, in __init__
    self._from_file(args[0], **kwargs)
  File "C:\Anaconda3\envs\sfepy_py38_env\lib\site-packages\pyvista\core\dataobject.py", line 69, in _from_file
    data = pyvista.read(filename, **kwargs)
  File "C:\Anaconda3\envs\sfepy_py38_env\lib\site-packages\pyvista\utilities\fileio.py", line 159, in read
    raise FileNotFoundError(f'File ({filename}) not found')
FileNotFoundError: File (C:\Users\FL232714\AppData\Local\Temp\tmp9_79fnzj\result.vtk) not found
```

**Comment by flothesof** [comment]
What is interesting is that in your output, the path in line 1 is not the same as the path in line 2, while for me it seems to be.

**Comment by rc** [comment]
So it looks like the line 374: `fname = edit_filename(filename, suffix=suffix)` does not do its job properly - can you trace it?

**Comment by flothesof** [comment]
Thank you for the suggestion, I’ll try this tomorrow.

**Comment by flothesof** [comment]
When I enter `edit_filename`, args are:
```
filename = {str} 'C:\\Users\\FL232714\\AppData\\Local\\Temp\\tmp8floikix\\result.vtk'
new_ext = {NoneType} None
prefix = {str} ''
suffix = {str} ''
```

When I exit, `fname = 'C:\\Users\\FL232714\\AppData\\Local\\Temp\\tmp8floikix\\result.vtk'`.

Or maybe the problem is rather with the line `filename = problem.get_output_name(suffix=suffix)` ?

In that case, when I enter, I have 
```
extra = {NoneType} None
mode = {NoneType} None
self = {Problem} Problem:problem_from_conf\n  _restart_filenames:\n    list: []\n  active_only:\n    True\n  conf:\n    ProblemConf\n  conf_materials:\n    dict with keys: []\n  conf_variables:\n    dict with keys: ['variable_p_1__0', 'variable_q_1__1', 'variable_p_2__2', 'variable_
suffix = {NoneType} None
```
and it returns `'C:\\Users\\FL232714\\AppData\\Local\\Temp\\tmpsqfwywwi\\result.vtk'`.

**Comment by rc** [comment]
I see, so it is already the `suffix` arg that is wrong - it should be equal to `_Omega_1` - what is the contents of the `views` variable? And is 
```
    'acoustics/acoustics3d.py': {
        '_Omega_1': {
            'camera': [75, 135, 1.4],
            'grid_vector1': [1.2, 0, 0],
        },
        '_Omega_2': {
            'camera': [75, 135, 1],
            'grid_vector1': [1.2, 0, 0],
        },
    },
```
in the `custom` dict at the beginning of the file?

**Comment by rc** [comment]
Maybe this change would help?
```
         if problem is not None:
-            if ebase in custom:
+            if ebase.replace('/', os.path.sep) in custom:
```

**Comment by flothesof** [comment]
Yes, I have the `custom` settings (I started from a fairly recent git commit 49ad0c93f65e868a49edeefe72dff85d2a96b740).

I understand why this doesn’t work based on your change. But even with you change,`ebase` is not in the `custom` dict.

This seems to be due to the fact that the dict keys are slashes (/), while on windows the paths are with written with anti-slashes (\).

I’ll see if I can get it to work with minimal modifications.

**Comment by rc** [comment]
Is there some other problem then?

**Comment by flothesof** [comment]
Yes, there are a couple of examples that error after running, when trying to generate plots due to missing named fields in the outputs:

- 'advection_1D.py', # missing field
 - 'elastic_shifted_periodic.py', # missing field in output
 - 'piezo_elasticity.py', # missing field in output

Also, when generating the rst documents, I have two additional errors due to imports of petsc4py that is missing on my machine:
- 'poisson_parallel_interactive.py', # rst petsc4py import
- 'biot_parallel_interactive.py' # rst petsc4py import

**Comment by rc** [comment]
Try
```
 
-                resview_plot(fname, fig_filename, kwargs)
+                try:
+                    resview_plot(fname, fig_filename, kwargs)
+
+                except Exception as exc:
+                    output(f'with plot arguments: {kwargs}')
+                    output(f'failed with {exc}')
 ```
and post the output for the failed examples. Thanks!

**Comment by flothesof** [comment]
I’m afraid there’s more problems than that. 

Two examples : 

- some examples fail at the plotting section, in this case advection_1D.py
```
sfepy:     trying "dg\advection_1D.py"...
sfepy: displaying results from "C:\Users\FL232714\AppData\Local\Temp\tmp3t10vho9\result.123.vtk"
sfepy: to "doc\images/gallery\dg-advection_1D.png"...
sfepy:   resview_plot with arguments: C:\Users\FL232714\AppData\Local\Temp\tmp3t10vho9\result.123.vtk, C:\Users\FL232714\Documents\Python workspace\Scripts\2020_sfepy\sfepy\doc\images/gallery\dg-advection_1D.png, Struct
  axes_options:
    list: []
  axes_visibility:
    False
  camera:
    list: [225, 75, 1]
  color_map:
    viridis
  factor:
    1.0
  fields:
    list: []
  fields_map:
    list: []
  force_view_3d:
    False
  grid_vector1:
    list: [1.2, 0, 0]
  grid_vector2:
    list: [0, -1.2, 0]
  isosurfaces:
    0
  label_position:
    list: [-1, -1, 0, 0.2]
  max_plots:
    3
  opacity:
    1.0
  outline:
    False
  scalar_bar_position:
    list: [0.04, 0.92, 1.7, 0]
  scalar_bar_size:
    list: [0.15, 0.06]
  show_edges:
    False
  show_labels:
    False
  show_scalar_bars:
    True
  step:
    0
  view_2d:
    True
  warp:
    None
sfepy:   failed with 'Data array (mat_id) not present in this dataset.'
sfepy: ...done
C:\Anaconda3\envs\sfepy_py38_env\lib\site-packages\pyvista\core\pointset.py:205: PyvistaDeprecationWarning: You did not specify a value for `inplace` and the default value will be changing to `False` in future versions for point-based meshes (e.g., `PolyData`). Please make sure you are not assuming this to be an inplace operation.
  warnings.warn(DEFAULT_INPLACE_WARNING, PyvistaDeprecationWarning)
sfepy: ...done
```

- while others fail at the running stage
```
sfepy:     trying "dg\advection_2D.py"...
sfepy: ***** failed! *****
```
